erDiagram
    Project {
        id int PK "auto_increment"
        friendly_name string "The user-friendly name of the project"
        file_name string "The file name originally imported"
        content string "The text content of the project"
    }
